# @format

version: '3'
services:
  frontend_debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
      network: host

    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
